name: 3dgs_dk
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py37h5e8e339_1
  - async-timeout=3.0.1=py_1000
  - attrs=23.2.0=pyh71513ae_0
  - blinker=1.6.3=pyhd8ed1ab_0
  - brotli-python=1.0.9=py37hd23a5d3_7
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cachetools=5.3.3=pyhd8ed1ab_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py37h43b0acd_1
  - chardet=4.0.0=py37h89c1867_3
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.3=py37h89c1867_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=38.0.2=py37h5994e8b_1
  - cuda-version=11.6=hca96458_3
  - cudatoolkit=11.6.2=hfc3e2af_13
  - cudnn=8.8.0.121=hcdd5f01_4
  - freetype=2.12.1=h267a509_2
  - google-auth=2.17.3=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpc-cpp=1.48.1=h30feacc_1
  - grpcio=1.48.1=py37he7b19e7_1
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py37h89c1867_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jpeg=9e=h0b41bf4_3
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libblas=3.9.0=21_linux64_openblas
  - libcblas=3.9.0=21_linux64_openblas
  - libdeflate=1.14=h166bdaf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgomp=13.2.0=h807b86a_5
  - liblapack=3.9.0=21_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.21.8=h6239696_0
  - libsqlite=3.45.1=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.4.0=h82bc61c_5
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=hd590300_5
  - magma=2.5.4=hc72dce7_4
  - markupsafe=2.1.1=py37h540881e_1
  - mkl=2022.1.0=hc2b9512_224
  - multidict=6.0.2=py37h540881e_1
  - nccl=2.20.5.1=h0800d71_0
  - ncurses=6.4=h59595ed_2
  - ninja=1.11.1=h924138e_0
  - numpy=1.21.6=py37h976b520_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.2.1=hd590300_0
  - pillow=9.2.0=py37h850a105_2
  - pip=22.3.1=pyhd8ed1ab_0
  - plyfile=0.8.1=pyhd8ed1ab_0
  - protobuf=4.21.8=py37hd23a5d3_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.5.1=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=cuda112py37h6a44366_201
  - pytorch-mutex=1.0=cuda
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sqlite=3.45.1=h2c6b66d_0
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py37h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=0.12.1=py37_cu116
  - torchvision=0.13.1=cpu_py37h164cc8f_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - werkzeug=2.2.3=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yarl=1.7.2=py37h540881e_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - asttokens==2.4.1
    - cycler==0.11.0
    - executing==2.0.1
    - fonttools==4.38.0
    - gputil==1.4.0
    - icecream==2.1.3
    - imageio==2.31.2
    - imageio-ffmpeg==0.5.1
    - kiwisolver==1.4.5
    - markdown==3.3.3
    - matplotlib==3.5.3
    - opencv-python==4.9.0.80
    - packaging==24.0
    - pandas==1.3.5
    - psutil==5.9.8
    - pygments==2.17.2
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - torch-tb-profiler==0.4.3